name: Deploy to TimeWeb via SSH
on:
  push:
    branches: [main] # запускать только при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: vh450.timeweb.ru
          username: ch73371
          password: ${{ secrets.TIMEWEB_SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/public_html  # или другая папка сайта
            git fetch origin
            git reset --hard origin/main
            # Дополнительные команды (если нужно):
            # composer install
            # npm run build
